format = "$directory${custom.jj}$character"

[directory]
style = "blue"
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
disabled = true
format = "[$branch]($style)"
style = "bright-black"

[git_status]
disabled = true
format = "[(*$conflicted$untracked$modified$staged$renamed$deleted) ($ahead_behind )](red)"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"

[git_state]
disabled = true
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship", "--no-jj-prefix", "--no-git-prefix"]
format = "$output "
