format = "$directory${custom.jj}$character"

[directory]
style = "blue"
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship", "--no-jj-prefix", "--no-git-prefix"]
format = "$output "
